version: "3"
services:
  site:
    command: jekyll serve --incremental
    image: jekyll/jekyll:latest
    volumes:
      - $PWD:/srv/jekyll
      - $PWD/vendor/bundle:/usr/local/bundle
    ports:
      - 5000:5000
